ANT_SPEED = 3
SPIDER_SPEED = 2.5

ANT_COUNT = 10
SPIDER_COUNT = 1
SUGAR_COUNT = 6

GAME_AREA_WIDTH, GAME_AREA_HEIGHT = 1280, 800

INIT_SUGAR_AMOUNT = 1000/SUGAR_COUNT
ANT_SUGAR_CONSUMPTION = 1/SUGAR_COUNT

ANT_COLLISION_DIAMETER = 15
SPIDER_COLLISION_DIAMETER = 35

USE_ACCELERATION = True
ACCELERATION_DECAY = 0.5
